Fix occasional ValueError
Some phrases caused a traceback in logs;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Speak.activity/espeak.py", line 116, in handoff
    peak = numpy.core.max(wave)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

Adding debug logging showed `when` and `last` were equal, so this was an
off-by-one mistake.

Change the conditional test.

Fixes https://github.com/sugarlabs/speak/issues/16